# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


env:
  global:
  - R_CHECK_ARGS="--timings"

r_packages:
  - archivist
  - ggplot2
  - covr

r_github_packages:
  - ModelOriented/ingredients
  - ModelOriented/iBreakDown


after_success:
  - Rscript -e 'library(covr); codecov()'

